import { useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { Photo } from '@/components/Photo';
import { PromptInput } from '@/components/PromptInput';
import { Chip } from '@/components/Chip';
import { ScrollSequence } from '@/components/ScrollSequence';
import { images } from '@/lib/images';
import { navigate, planHref } from '@/lib/router';
import { MARKETING, EXAMPLE_PROMPTS } from '@/lib/content';
import heroManifest from '@/lib/hero-manifest.json';
import type { SequenceManifest } from '@/lib/sequence';

/**
 * Hero — full-bleed scroll-scrubbed background with a scrim for legibility, the display
 * headline, subhead, and a live prompt box that routes straight into the planner
 * (autostart). The three example prompts sit below as chips that seed the same flow. One
 * primary action only.
 *
 * The background is a frame sequence drawn to a canvas and advanced by scroll position —
 * see `@/components/ScrollSequence` and the README's "Scroll-scrubbed hero" section. Every
 * visitor who does not qualify for the scrub (reduced motion, narrow viewport, slow or
 * metered connection) gets a single static frame instead, and until the frame sets have
 * been generated the hero falls back to the destination photo it has always used.
 *
 * Note the headline, subhead, prompt, and chips are ordinary DOM stacked over the canvas,
 * not baked into the frames: selectable, translatable, and read in order by a screen reader.
 */

/** Generated by `scripts/build-hero-frames.sh`. `frames: 0` until it has been run. */
const HERO_SEQUENCE = heroManifest as SequenceManifest;

export function Hero() {
  const [value, setValue] = useState('');
  const reduce = useReducedMotion();

  const go = (seed: string) => {
    const trimmed = seed.trim();
    if (!trimmed) return;
    navigate(planHref({ seed: trimmed, autostart: true }));
  };

  const reveal = (delay: number) =>
    reduce
      ? { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { duration: 0.2 } }
      : {
          initial: { opacity: 0, y: 16 },
          animate: { opacity: 1, y: 0 },
          transition: { duration: 0.5, ease: [0.22, 1, 0.36, 1] as const, delay },
        };

  return (
    <ScrollSequence
      manifest={HERO_SEQUENCE}
      // The section bleeds up under the sticky 4rem nav, so it needs 4rem of extra height
      // to still cover the whole viewport once pinned at the top.
      className="-mt-16 h-[calc(100svh+4rem)] min-h-[600px]"
      fallback={
        <Photo
          image={images.for('greece')}
          imageKey="greece"
          alt=""
          eager
          className="absolute inset-0 h-full w-full"
        />
      }
    >
      {/* Legibility scrims: darker on the left where the text sits, fading right. */}
      <div
        className="absolute inset-0 -z-10 bg-gradient-to-r from-scrim/80 via-scrim/45 to-transparent"
        aria-hidden
      />
      <div
        className="absolute inset-0 -z-10 bg-gradient-to-b from-scrim/35 to-transparent"
        aria-hidden
      />

      <div className="flex h-full items-center">
        <div className="mx-auto w-full max-w-site px-6 pb-20 pt-28">
          <div className="max-w-2xl">
            <motion.h1 {...reveal(0)} className="font-display text-display font-semibold text-white">
              {MARKETING.hero.headline}
            </motion.h1>
            <motion.p
              {...reveal(0.08)}
              className="mt-4 max-w-xl text-lg leading-relaxed text-white/90"
            >
              {MARKETING.hero.subhead}
            </motion.p>

            <motion.div {...reveal(0.16)} className="mt-8 max-w-xl">
              <PromptInput
                variant="hero"
                value={value}
                onValueChange={setValue}
                onSubmit={go}
                placeholder={MARKETING.hero.promptPlaceholder}
              />
            </motion.div>

            <motion.ul
              {...reveal(0.24)}
              className="mt-4 flex flex-wrap gap-2"
              aria-label="Example trips"
            >
              {EXAMPLE_PROMPTS.map((ex) => (
                <li key={ex.tag}>
                  <Chip onClick={() => go(ex.prompt)} aria-label={`Plan: ${ex.label}`}>
                    {ex.label}
                  </Chip>
                </li>
              ))}
            </motion.ul>
          </div>
        </div>
      </div>
    </ScrollSequence>
  );
}
