#!/usr/bin/env bash
#
# Generate LQIP placeholders for the /collection page.
#
# Each placeholder is a ~20px-wide JPEG of the real photo, inlined as a data URI and
# CSS-blurred at render.
#
# Also checks that every photo returns HTTP 200 before writing. A curated ID that 404s falls
# through to the fallback in lib/images.ts and shows the wrong place.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WEB_DIR="$(dirname "$SCRIPT_DIR")"
IMAGES_TS="$WEB_DIR/src/lib/images.ts"
OUT="$WEB_DIR/src/components/collection/lqip.generated.ts"

# Pillow does the resize (see below). stdin-piped from curl because Python's urllib cannot
# verify certificates behind some proxies, while curl can.
PY_SHRINK='
import base64, io, sys
from PIL import Image
im = Image.open(io.BytesIO(sys.stdin.buffer.read())).convert("RGB")
w = 16
h = max(1, round(im.height * w / im.width))
buf = io.BytesIO()
im.resize((w, h), Image.LANCZOS).save(buf, "JPEG", quality=35, optimize=True)
sys.stdout.write(base64.b64encode(buf.getvalue()).decode())
'

KEYS="aegean_port aegean_table cyclades_alley aegean_terrace greece sunset athens family group santorini amalfi beach lisbon kyoto prague porto flight meal museum viewpoint hike nightlife"

mkdir -p "$(dirname "$OUT")"
{
  echo "// Generated by scripts/build-lqip.sh. Do not edit."
  echo "// ~20px JPEGs of the real photographs, inlined and CSS-blurred while the full"
  echo "// image loads. Regenerate after changing the curated set in lib/images.ts."
  echo "export const LQIP: Record<string, string> = {"
} > "$OUT"

fail=0
for key in $KEYS; do
  id=$(grep -oE "^  ${key}: u\('[^']+'\)" "$IMAGES_TS" | grep -oE "'[^']+'" | tr -d "'" || true)
  if [ -z "$id" ]; then
    printf '  %-12s MISSING from lib/images.ts\n' "$key" >&2; fail=1; continue
  fi
  full="https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=640&q=70"
  code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 20 "$full")
  if [ "$code" != "200" ]; then
    printf '  %-12s HTTP %s  (%s)\n' "$key" "$code" "$id" >&2; fail=1; continue
  fi
  # Downscale locally: Unsplash clamps tiny `w` values and returns ~3.5KB regardless, and
  # ffmpeg's mjpeg encoder emits full Huffman tables, so a 16px frame still costs ~3.4KB.
  # Pillow gets the same image to ~370 bytes.
  b64=$(curl -sS --max-time 20 "https://images.unsplash.com/photo-${id}?fm=jpg&w=96&q=40&fit=crop" \
    | python3 -c "$PY_SHRINK")
  printf '  %s: "data:image/jpeg;base64,%s",\n' "$key" "$b64" >> "$OUT"
  printf '  %-12s ok  (%s bytes)\n' "$key" "$(( ${#b64} * 3 / 4 ))"
done

echo "};" >> "$OUT"
[ "$fail" -eq 0 ] || { echo; echo "one or more photos failed. Fix lib/images.ts before building" >&2; exit 1; }
echo
echo "wrote ${OUT#"$WEB_DIR/"}"
