/**
 * live-run — exercise the ten-agent LangGraph path ONCE against the real API and write the
 * transcript to docs/live-run.md.
 *
 * Why this exists: every one of the package's tests drives a stub model. That is deliberate and
 * correct for CI, but it means the real request shape was never exercised — which is exactly how
 * the `top_p: -1` bug survived long enough to silently disable the whole LLM path in production
 * (every call 400'd, `decide()` swallowed it, and the deterministic fallback answered instead;
 * the plans looked fine). A stub cannot catch that class of bug. One real run can.
 *
 * This is a one-off command, not a config change. `WAYFARE_LLM_ORCHESTRATOR` stays unset by
 * default everywhere else; nothing here writes a key, edits a default, or touches apps/web.
 *
 *   ANTHROPIC_API_KEY=... WAYFARE_LLM_ORCHESTRATOR=true \
 *     pnpm --dir packages/orchestrator-llm exec tsx scripts/live-run.mts
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { mockProviderRegistry, type TravelerProfile } from "@wayfare/orchestrator";
import { createOrchestrator, readConfig } from "../src/index.js";
import type { LlmPlanResult } from "../src/graph.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(HERE, "..");

/** Sonnet 5 intro pricing, $/MTok in-out. Matches gen-persona-data's table. */
const PRICE_IN = 2 / 1_000_000;
const PRICE_OUT = 10 / 1_000_000;

const prompt = "5 day foodie trip to Naxos in September, budget around €1800 for two";
const traveler: TravelerProfile = {
  signals: ["foodie on a budget", "wants to be central", "hates 6am flights"],
  partySize: { adults: 2 },
  mustHaves: [],
  avoid: [],
} as unknown as TravelerProfile;

const config = readConfig(process.env);
if (!config.enabled) {
  console.error(
    "live-run: WAYFARE_LLM_ORCHESTRATOR is not the literal \"true\" — the orchestrator would " +
      "fall back to the deterministic path and this run would prove nothing. Aborting.",
  );
  process.exit(1);
}
if (!process.env.ANTHROPIC_API_KEY) {
  console.error("live-run: ANTHROPIC_API_KEY is not set. Aborting.");
  process.exit(1);
}

const events: { agent: string; event: string; detail?: unknown }[] = [];
const started = Date.now();

const planner = createOrchestrator(mockProviderRegistry(), {
  onEvent: (e: { agent?: string; event?: string; detail?: unknown }) =>
    // The detail is the point: an `agent_error` with no payload says the LLM path failed but
    // not why, which is the same blindness that let top_p:-1 survive.
    events.push({
      agent: String(e.agent ?? "?"),
      event: String(e.event ?? "?"),
      ...(e.detail ? { detail: e.detail } : {}),
    }),
});

let result: LlmPlanResult | undefined;
let failure: string | undefined;
try {
  result = (await planner.plan(prompt, traveler)) as LlmPlanResult;
} catch (err) {
  failure = err instanceof Error ? `${err.name}: ${err.message}` : String(err);
}
const wallMs = Date.now() - started;

const u = result?.usage;
const cost = u ? u.inputTokens * PRICE_IN + u.outputTokens * PRICE_OUT : 0;

const lines: string[] = [];
lines.push("# Live run — the ten-agent LangGraph path against the real API");
lines.push("");
lines.push(
  "Generated by `scripts/live-run.mts`. Every test in this package drives a stub model, which " +
    "is right for CI but means the real request shape is never exercised — how the `top_p: -1` " +
    "bug survived. This is the one run that proves the path works end to end.",
);
lines.push("");
lines.push("**The flag stays off by default.** This is a one-off command, not a config change.");
lines.push("");
lines.push("```");
lines.push(`prompt:   ${prompt}`);
lines.push(`signals:  ${JSON.stringify(traveler.signals)}`);
lines.push(`model:    ${config.model}`);
lines.push(`agents:   ${[...config.agents].join(", ")}`);
lines.push(`ceilings: ${config.maxCalls} calls / ${config.maxTokens} tokens`);
lines.push("```");
lines.push("");

if (failure) {
  lines.push("## Result: FAILED");
  lines.push("");
  lines.push("```");
  lines.push(failure);
  lines.push("```");
} else if (u) {
  lines.push("## Usage");
  lines.push("");
  lines.push(
    `- model calls: **${u.calls}** of ${config.maxCalls} · tool calls: **${u.toolCalls}**` +
      `${u.capped ? ` · **CAPPED (${u.cappedReason})**` : ""}`,
  );
  lines.push(`- tokens: **${u.totalTokens.toLocaleString()}** (${u.inputTokens.toLocaleString()} in / ${u.outputTokens.toLocaleString()} out) of ${config.maxTokens.toLocaleString()}`);
  lines.push(`- cost: **$${cost.toFixed(4)}** at Sonnet 5 intro pricing ($2/$10 per MTok)`);
  lines.push(`- wall clock: **${(wallMs / 1000).toFixed(1)}s**`);
  lines.push("");
  lines.push("### Per agent");
  lines.push("");
  lines.push("| agent | LLM | in | out | tool calls | ms |");
  lines.push("|---|---|---|---|---|---|");
  for (const a of u.perAgent) {
    lines.push(
      `| ${a.agent} | ${a.llm ? "yes" : "fallback"} | ${a.inputTokens} | ${a.outputTokens} | ${a.toolCalls} | ${a.ms} |`,
    );
  }
  lines.push("");
  lines.push("### Plan result");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(result, null, 2).slice(0, 12_000));
  lines.push("```");
}

lines.push("");
lines.push("### Trace events");
lines.push("");
lines.push("```");
lines.push(
  events
    .map((e) => `${e.agent}: ${e.event}${e.detail ? ` ${JSON.stringify(e.detail).slice(0, 300)}` : ""}`)
    .join("\n")
    .slice(0, 8000),
);
lines.push("```");
lines.push("");

const out = join(PKG_ROOT, "docs", "live-run.md");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${lines.join("\n")}\n`);

console.log(`live-run: wrote ${out}`);
if (failure) {
  console.error(`live-run: FAILED — ${failure}`);
  process.exit(1);
}
console.log(
  `live-run: ${u?.calls} calls, ${u?.totalTokens} tokens, $${cost.toFixed(4)}, ${(wallMs / 1000).toFixed(1)}s`,
);
