import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { cn } from '@/lib/cn';
import {
  decideSequence,
  posterUrl,
  type SequenceDecision,
  type SequenceManifest,
} from '@/lib/sequence';
import { useFrameSequence, type DecodedFrame } from '@/lib/useFrameSequence';
import { prefetchScrollScrub, useScrollScrub } from '@/lib/useScrollScrub';

/**
 * A full-viewport section whose background animation advances frame by frame with scroll,
 * then releases into normal page flow. See `apps/web/README.md` § "Scroll-scrubbed hero".
 *
 * Draws decoded stills to a canvas instead of scrubbing a `<video>`: video seeking is
 * asynchronous and keyframe-quantised, so it stutters and snaps.
 */

export interface ScrollSequenceProps {
  /** Generated by `scripts/build-hero-frames.sh`. Must be a stable object reference. */
  manifest: SequenceManifest;
  /** Overlay content: real DOM, above the canvas. Put the headline here, not in frames. */
  children?: ReactNode;
  /** Sizing/positioning for the pinned section. Defaults to a full `100svh` block. */
  className?: string;
  /** Viewports of scroll the scrub consumes before the hero releases. */
  viewports?: number;
  /** GSAP scrub: `true` locks to the finger, a number is seconds of catch-up smoothing. */
  scrub?: number | boolean;
  /** Poster alt text. Leave empty when the headline beside it already says it. */
  posterAlt?: string;
  /** Background used when the manifest is empty, i.e. the frame sets are not generated yet. */
  fallback?: ReactNode;
  /** Renders a corner readout of mode, decode progress, and scrub position. */
  debug?: boolean;
}

/** Device-pixel-ratio ceiling. Past 2× the sequence gains nothing visible and costs fill-rate. */
const MAX_DPR = 2;

/**
 * Draw `frame` to fill `cw`×`ch` without distortion (`object-fit: cover`). All arithmetic is
 * in device pixels: `ctx.scale(dpr, dpr)` with CSS-pixel maths drifts by sub-pixels and shows
 * as a shimmering 1px seam at the edges during a scrub.
 */
function drawCover(
  ctx: CanvasRenderingContext2D,
  frame: DecodedFrame,
  cw: number,
  ch: number,
): void {
  const fw = frame.width;
  const fh = frame.height;
  if (!fw || !fh || !cw || !ch) return;

  const scale = Math.max(cw / fw, ch / fh);
  const dw = fw * scale;
  const dh = fh * scale;
  ctx.drawImage(frame, (cw - dw) / 2, (ch - dh) / 2, dw, dh);
}

export function ScrollSequence({
  manifest,
  children,
  className,
  viewports = 2,
  scrub = 0.5,
  posterAlt = '',
  fallback,
  debug = false,
}: ScrollSequenceProps) {
  const sectionRef = useRef<HTMLElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  // Re-evaluated only when the reduced-motion preference changes, not on resize: flipping
  // from static to pinned mid-session would move the page under the visitor.
  const [decision, setDecision] = useState<SequenceDecision>(() => decideSequence());
  const [pinSkipped, setPinSkipped] = useState<string | null>(null);

  useEffect(() => {
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    const onChange = () => setDecision(decideSequence());
    mq.addEventListener('change', onChange);
    return () => mq.removeEventListener('change', onChange);
  }, []);

  const hasSequence = manifest.frames > 0;
  const wantsScrub = hasSequence && decision.mode === 'scrub';
  const sequence = useFrameSequence(manifest, decision.variant, wantsScrub);

  // Load the GSAP chunk while the frames decode, not after.
  useEffect(() => {
    if (wantsScrub) prefetchScrollScrub();
  }, [wantsScrub]);

  // Pin only once enough frames are decoded to scrub smoothly. Until then (and always for
  // reduced-motion, narrow and slow-connection visitors) the section is a normal block
  // showing the poster.
  const scrubReady = wantsScrub && sequence.ready;

  /** Whether the hero is on screen. Gates the render loop; see the observer below. */
  const visibleRef = useRef(false);
  const rafRef = useRef<number | null>(null);
  /** Last frame index committed to the canvas. -1 forces the next tick to redraw. */
  const lastIndexRef = useRef(-1);
  /** The frame currently on the canvas, retained so a resize can repaint without the loop. */
  const lastFrameRef = useRef<DecodedFrame | null>(null);
  const [painted, setPainted] = useState(false);

  /** Match the backing store to the CSS box × DPR. Returns device-pixel dimensions. */
  const sizeCanvas = useCallback((canvas: HTMLCanvasElement): [number, number] => {
    const dpr = Math.min(window.devicePixelRatio || 1, MAX_DPR);
    const width = Math.round(canvas.clientWidth * dpr);
    const height = Math.round(canvas.clientHeight * dpr);
    if (canvas.width !== width || canvas.height !== height) {
      canvas.width = width;
      canvas.height = height;
      // Resizing a canvas clears it, so whatever was drawn is gone.
      lastIndexRef.current = -1;
    }
    return [width, height];
  }, []);

  const paint = useCallback(
    (frame: DecodedFrame, index?: number) => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      // `alpha: false` lets the compositor skip per-pixel blending; the frames are opaque
      // and cover the full box, so there is also no need to clearRect between draws.
      const ctx = canvas.getContext('2d', { alpha: false });
      if (!ctx) return;
      const [w, h] = sizeCanvas(canvas);
      drawCover(ctx, frame, w, h);
      lastFrameRef.current = frame;
      // Mirrors the drawn frame onto the element for devtools and tests.
      if (index !== undefined) canvas.dataset.frame = String(index);
      setPainted(true);
    },
    [sizeCanvas],
  );

  const progressRef = useScrollScrub({
    target: sectionRef,
    enabled: scrubReady,
    viewports,
    scrub,
    onSkip: setPinSkipped,
  });

  /**
   * The single render loop. It reads the latest progress from a ref and draws. Drawing in
   * the scroll callback would tie draw rate to input event rate, and a trackpad fires far
   * faster than the display refreshes. The loop exits when the hero leaves the viewport.
   */
  const startLoopRef = useRef(() => {});
  startLoopRef.current = () => {
    const tick = () => {
      const total = sequence.total;
      const progress = progressRef.current;
      const index = Math.min(total - 1, Math.max(0, Math.round(progress * (total - 1))));

      if (debug && canvasRef.current) {
        const el = canvasRef.current;
        el.dataset.progress = progress.toFixed(4);
        el.dataset.ticks = String((Number(el.dataset.ticks) || 0) + 1);
      }

      if (index !== lastIndexRef.current) {
        const frame = sequence.nearest(index);
        if (frame) {
          paint(frame, index);
          // Only commit the index once something was actually drawn, so a hole in a
          // partially loaded set is retried on the next tick instead of being skipped.
          lastIndexRef.current = index;
        }
      }

      if (visibleRef.current) {
        rafRef.current = requestAnimationFrame(tick);
      } else {
        rafRef.current = null;
      }
    };
    rafRef.current = requestAnimationFrame(tick);
  };

  useEffect(
    () => () => {
      if (rafRef.current !== null) cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
    },
    [],
  );

  // First paint, independent of the loop: once frames are ready, draw the frame for the
  // current scroll position. Otherwise the canvas stays transparent until the visitor scrolls.
  useEffect(() => {
    if (!scrubReady) return;
    const total = sequence.total;
    const index = Math.min(total - 1, Math.max(0, Math.round(progressRef.current * (total - 1))));
    const frame = sequence.nearest(index);
    if (frame) {
      paint(frame, index);
      lastIndexRef.current = index;
    }
  }, [scrubReady, sequence, paint, progressRef]);

  /**
   * Gate the render loop on the hero's own visibility. This is an IntersectionObserver
   * because ScrollTrigger's `isActive` is not reliably set during the initial refresh and
   * `onToggle` never fires for a trigger's initial state, so a hero pinned at the top on
   * first load would never start the loop.
   */
  useEffect(() => {
    const el = sectionRef.current;
    if (!el) return;
    const observer = new IntersectionObserver((entries) => {
      const visible = entries.some((entry) => entry.isIntersecting);
      visibleRef.current = visible;
      if (visible && rafRef.current === null) startLoopRef.current();
    });
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  // Keep the backing store correct across resizes and orientation changes. The retained
  // frame is repainted directly, without the loop.
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const observer = new ResizeObserver(() => {
      const frame = lastFrameRef.current;
      if (frame) paint(frame);
    });
    observer.observe(canvas);
    return () => observer.disconnect();
  }, [paint]);

  const poster = posterUrl(manifest, decision.variant);

  return (
    <section
      ref={sectionRef}
      className={cn('relative isolate overflow-hidden', className ?? 'h-svh min-h-[600px]')}
    >
      <div className="absolute inset-0 -z-10">
        {/*
         * The poster is a real <img> at high fetch priority. It is the first frame of the
         * sequence, and in static mode it is the whole hero. It stays mounted under the
         * canvas after the handoff.
         */}
        {hasSequence ? (
          <img
            src={poster}
            alt={posterAlt}
            // React 18 does not map the camelCase `fetchPriority` prop onto the DOM attribute
            // (React 19 does), so it is spelled lowercase and spread past JSX's prop checking.
            {...({ fetchpriority: 'high' } as Record<string, string>)}
            decoding="async"
            className="absolute inset-0 h-full w-full object-cover"
          />
        ) : (
          fallback
        )}
        <canvas
          ref={canvasRef}
          aria-hidden
          className={cn(
            'absolute inset-0 h-full w-full transition-opacity duration-500 ease-out',
            painted ? 'opacity-100' : 'opacity-0',
          )}
        />
      </div>

      {children}

      {debug && (
        <div className="pointer-events-none absolute bottom-4 right-4 z-50 rounded-sm bg-scrim/80 px-3 py-2 font-mono text-[11px] leading-relaxed text-white">
          <div>mode: {decision.mode}</div>
          <div>variant: {decision.variant}</div>
          <div>reason: {decision.reason}</div>
          <div>
            decoded: {sequence.decoded}/{sequence.total}
          </div>
          <div>scrub: {!hasSequence ? 'no manifest' : scrubReady ? 'engaged' : 'waiting'}</div>
          {pinSkipped && <div>pin skipped: {pinSkipped}</div>}
          {sequence.error && <div>error: {sequence.error.message}</div>}
        </div>
      )}
    </section>
  );
}
