import { useEffect, useRef, useState } from 'react';
import { Photo } from '@/components/Photo';
import { ScrollSequence } from '@/components/ScrollSequence';
import { images } from '@/lib/images';
import { MARKETING } from '@/lib/content';
import heroManifest from '@/lib/hero-manifest.json';
import type { SequenceManifest } from '@/lib/sequence';
import { BookingPanel } from './BookingPanel';
import { BookingSection } from './BookingSection';
import { Chapter } from './Chapter';
import { CollectionNav } from './CollectionNav';
import { InlineBooking } from './InlineBooking';
import { CHAPTERS } from './chapters';

/**
 * `/collection` — a chaptered scroll narrative for Wayfare.
 *
 * It opens on the scrubbed harbour sequence (the same one the landing page uses), then
 * releases into six chapters. The palette is the project's own azure-on-white system from
 * TOKENS.md; what is borrowed from the reference is the *photo placement and motion* — a
 * held stage, one large frame against two or three small ones, and layers that travel at
 * different rates as you scroll. Not its colour scheme, and not its scroll hijacking.
 *
 * Native scroll throughout, indexable, with a real mobile layout.
 */

/** Generated by `scripts/build-hero-frames.sh`. `frames: 0` until it has been run. */
const HERO_SEQUENCE = heroManifest as SequenceManifest;

export function CollectionPage() {
  const [bookingOpen, setBookingOpen] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  // The app is a client-rendered SPA with one index.html, so per-route metadata is set here.
  // A crawler that executes JS will index this; for guaranteed indexing this route wants
  // prerendering or SSR — noted in the README rather than silently assumed.
  useEffect(() => {
    const prevTitle = document.title;
    // This page is the front door at `/`, so there it keeps the site title from index.html
    // rather than renaming the home page after the route it also answers on.
    if (window.location.pathname !== '/') document.title = 'The Collection — Wayfare';
    const meta = document.querySelector('meta[name="description"]');
    const prevDesc = meta?.getAttribute('content') ?? null;
    meta?.setAttribute(
      'content',
      'Six chapters of trips you can actually take — planned, priced and sourced. Book from anywhere on the page.',
    );
    return () => {
      document.title = prevTitle;
      if (prevDesc !== null) meta?.setAttribute('content', prevDesc);
    };
  }, []);

  const openBooking = () => setBookingOpen(true);

  return (
    // Ground is `surface-2` (#EEF3FA) rather than pure white: a cool light blue that sits
    // under the photography without competing with it. It is a surface token, not azure —
    // TOKENS.md §6 keeps azure for interactive and brand elements.
    <div className="relative min-h-screen bg-surface-2 text-ink antialiased">
      <CollectionNav contentRef={contentRef} />

      <main>
        {/*
          The opening image: the harbour sequence, advanced frame by frame by scroll. The bar
          floats over it, so unlike the landing page there is no negative top margin to undo.
        */}
        <ScrollSequence
          manifest={HERO_SEQUENCE}
          className="h-svh min-h-[600px]"
          posterAlt=""
          fallback={
            <Photo
              image={images.for('greece')}
              imageKey="greece"
              alt=""
              eager
              className="absolute inset-0 h-full w-full"
            />
          }
        >
          {/* Scrims for legibility over the footage — the only dark surface on the page. */}
          <div
            className="absolute inset-0 -z-10 bg-gradient-to-r from-scrim/80 via-scrim/45 to-transparent"
            aria-hidden
          />
          <div
            className="absolute inset-0 -z-10 bg-gradient-to-b from-scrim/40 to-transparent"
            aria-hidden
          />

          <div className="flex h-full items-center">
            <div className="mx-auto w-full max-w-[1400px] px-5 sm:px-8">
              <p className="mb-6 font-mono text-[11px] uppercase tracking-[0.35em] text-white/60">
                The Collection
              </p>
              {/* Display split of MARKETING.hero.headline, broken by hand. */}
              <h1 className="text-white">
                <span className="block font-serif text-[clamp(2.6rem,6vw,4.6rem)] italic leading-[1.02]">
                  Your trip
                </span>
                <span className="mt-1 block font-display text-[clamp(2rem,4.6vw,3.4rem)] font-semibold uppercase leading-[1.05] tracking-[0.06em]">
                  <span className="block">PLANNED IN</span>
                  <span className="block">MINUTES</span>
                </span>
              </h1>
              <p className="mt-7 max-w-md text-lg leading-relaxed text-white/85">
                {MARKETING.hero.subhead}
              </p>
            </div>
          </div>
        </ScrollSequence>

        {/* Everything after the hero. The bar watches this block to decide its backdrop. */}
        <div ref={contentRef}>
          {CHAPTERS.map((chapter, i) => (
            <div key={chapter.id}>
              <Chapter chapter={chapter} />
              {/* Exactly two inline prompts, at the boundaries after chapters II and IV. */}
              {i === 1 && (
                <InlineBooking
                  line="Know the feeling you want? That is enough to start."
                  onBook={openBooking}
                />
              )}
              {i === 3 && (
                <InlineBooking
                  line="Every price you will see is sourced and dated."
                  onBook={openBooking}
                />
              )}
            </div>
          ))}

          <BookingSection />
        </div>
      </main>

      <footer className="border-t border-border">
        <div className="mx-auto flex max-w-[1400px] flex-col gap-2 px-5 py-10 text-xs text-ink-3 sm:px-8">
          <p>Wayfare — a trip planned for you from one sentence.</p>
          <p>
            Footage and photography are real. Prices shown in the planner carry their source
            and date.
          </p>
        </div>
      </footer>

      {/* No returnFocusTo: the panel hands focus back to whichever prompt opened it. */}
      <BookingPanel open={bookingOpen} onClose={() => setBookingOpen(false)} />
    </div>
  );
}
